from __future__ import annotations

HEAD_CORRECTION = 0.7
GAZE_CORRECTION = 0.5
SMOOTHING = 0.8
CAMERA_INDEX = 0

FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
FPS = 30

MAX_YAW_DEGREES = 18.0
MAX_PITCH_DEGREES = 14.0
MAX_ROLL_DEGREES = 12.0
MAX_GAZE_SHIFT = 0.35

FACE_MESH_MIN_DETECTION_CONFIDENCE = 0.5
FACE_MESH_MIN_TRACKING_CONFIDENCE = 0.5
FACE_MESH_MAX_FACES = 1

DEBUG = False

